config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'welcome#index', as: 'welcome'
  get '/privacypolicy', to: 'privacy_policy#index'
  get '/auth/ynab/callback', to: 'ynab#create'
  post '/signup', to: 'users#create'
  delete 'logout', to: 'sessions#destroy'

  get '/signup/ynab', to: 'ynab#new'
  get '/accounts/update', to: 'accounts#update', as: 'accounts_update'
  patch '/signup/profile', to: 'users#update'
  get '/signup/accounts', to: 'accounts#new'
  post '/signup/accounts', to: 'accounts#create'
  get '/dashboard', to: 'dashboard#index'
  get '/snowball/:amount', to: 'dashboard/snowball#index'

  get '/connections', to: 'connections#index'
  get '/accounts', to: 'accounts#index'
  get '/resources', to: 'resources#index'
  get '/profile', to: 'users#edit'

  get '/auth/google_oauth2/callback', to: 'users#create'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/views/partials/_navbar.html.erb
<aside>
  <section class="aside-user-info">
    <h1><%= current_user.first_name %></h1>
    <%= image_tag "#{current_user.image}" %>
  </section>
  <section class="aside-links">
    <p><%= link_to "Connections", connections_path %></p>
    <p><%= link_to "Resources", resources_path %></p>
    <p><%= link_to "Accounts", accounts_path %></p>
    <p><%= link_to "Profile", profile_path %></p>
  </section>
  <%= button_to "Logout", logout_path, class: "btn btn-primary logout-btn", method: :delete if current_user %>
</aside>